### ISSUE TITLE
Document/Update Tor bridges support

### ISSUE THREAD

**Issue by yahiheb** [WalletWasabi/WasabiDoc#1711]
According to:
https://github.com/zkSNACKs/WalletWasabi/pull/12749
https://github.com/zkSNACKs/WalletWasabi/pull/12940

https://docs.wasabiwallet.io/FAQ/FAQ-GeneralBitcoinPrivacy.html#my-country-isp-is-blocking-censoring-tor-how-can-i-use-wasabi-with-tor-bridges

This is probably obsolete so it should be updated maybe.

**Comment by yahiheb** [comment]
> - linux: TBD

@MarnixCroes Can you test this and get us the default Tor Browser path for Linux?

**Comment by MarnixCroes** [comment]
@kiminuo thank you, very useful.
Everything you mentioned should be covered in the PR I made https://github.com/WalletWasabi/WasabiDoc/pull/1757

**Comment by MarnixCroes** [comment]
fixed
