### ISSUE TITLE
webpage not updating/showing latest changes

### ISSUE THREAD

**Issue by MarnixCroes** [WalletWasabi/WasabiDoc#1730]
latest changes https://github.com/WalletWasabi/WasabiDoc/pull/1727 https://github.com/WalletWasabi/WasabiDoc/pull/1728 are not updated in the webpage

**Comment by yahiheb** [comment]
This is still a problem, https://github.com/WalletWasabi/WasabiDoc/pull/1731#issuecomment-2147392277

**Comment by yahiheb** [comment]
@lontivero The latest merged PRs are not being deployed since we moved the Wasabi repo, can you take a look why that's happening?

**Comment by yahiheb** [comment]
Lucas:
> The problem is the CI is bound to the previous organization. The same happened with the code repo.

**Comment by yahiheb** [comment]
The docs are up-to-date now. Closing.
