### ISSUE TITLE
My wallet was configured to MixTo itself,  It's balance is now decreasing, to I don't know where.

### ISSUE THREAD

**Issue by nostitos** [WalletWasabi/WasabiDoc#1843]
last 5 rounds show significant amount sent out.   To I assume itself.

I have concern that I didn't set it to send to itself but since the wallet I asked to be sent to originally was not opened it would have chosed the only option available - To sent to iself.

There's also the problem that I fear those coins are gone to ? and the issue that I have no way to really veify anything aside from resyncing the wallet from scratch hoping it was actually self-sent.

Was there not a balance update after every TX before?  I guess that got scraped.

**Comment by yahiheb** [comment]
This repo is not the right place for such issue, so I'm closing it.
Make sure to open another one here: https://github.com/WalletWasabi/WalletWasabi

**Comment by nostitos** [comment]
It just fixed itself after resyncing the wallet from 100,000 blocks earlier.
